#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int d1, d2;
	int c1 = 0, c2 = 0;
	float u, err = 0, m1 = 100, m2 = 100;
	float kp = 1.65;
	float ki = 0.012;
	float kd = 0.01;
	float kb = 0.000;

	int m_min = 12;
	int m_max = 90;

	float e_cur = 0, e_old = 0;
	eraseDisplay();
	displayCenteredBigTextLine(2,"LINE");
	displayCenteredBigTextLine(4,"TRACE");
	playSound(soundBeepBeep);
	wait1Msec(2000);
	eraseDisplay();
	d1 = SensorValue[S1];
	d2 = SensorValue[S2];
	displayCenteredBigTextLine(0, "left %d", d1);
	displayCenteredBigTextLine(2, "right %d", d2);
	d1 = d2 + 7;
	if (d1 > d2) {
		c1 = -abs(d1 - d2);
		c2 = 0;
	}
	else if (d2 > d1){
		c2 = -abs(d1 - d2);
		c1 = 0;
	}
	displayCenteredBigTextLine(4,"left %d",d1 + c1);
	displayCenteredBigTextLine(6,"right %d",d2 + c2);
	while(SensorValue[S3] == 0);
	playSound(soundBeepBeep);
	motor[motorB] = m1;
	motor[motorC] = m2;
	while(true) {
		d1 = SensorValue[S1] + c1;
		d2 = SensorValue [S2] + c2;
		//err += d1 - d2;
		e_cur = d1 - d2;
		if (abs(e_cur)<3) e_cur = 0;

		err += e_cur;
		if (abs(err)>10) err=sgn(err)*10;
		u = kp * e_cur + kd * (e_cur - e_old) + ki*err;
		m1 = m1 + u;
		m2 = m2 - u;
		if(m1 < m_min) m1 = m_min;
		if (m2 < m_min) m2 = m_min;
		if (m1 > m_max) m1 = m_max;
		if (m2 > m_max) m2 = m_max;
		motor[motorB] = m1;
		motor[motorC] = m2;
		e_old = e_cur;
	}
}
