#pragma config(Sensor, S3,     color,          sensorColorNxtFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void displayColor(word colorValue)
{
  string sColor;
  switch (colorValue)
  {
	  case BLACKCOLOR:    sColor = "Black";     break;
	  case BLUECOLOR:     sColor = "Blue";      break;
	  case GREENCOLOR:    sColor = "Green";     break;
	  case YELLOWCOLOR:   sColor = "Yellow";    break;
	  case REDCOLOR:      sColor = "Red";       break;
	  case WHITECOLOR:    sColor = "White";     break;
	  default:            sColor = "???";       break;
  }
  displayCenteredBigTextLine(3, sColor);
}

task main()
{
	eraseDisplay();
	displayCenteredBigTextLine(3, "Ambient");
	SensorType[color] = sensorColorNxtNONE;
	wait1Msec(1000);
	displayCenteredBigTextLine(3, "Red");
	SensorType[color] = sensorColorNxtRED;
	wait1Msec(1000);
	displayCenteredBigTextLine(3, "Green");
	SensorType[color] = sensorColorNxtGREEN;
	wait1Msec(1000);
	displayCenteredBigTextLine(3, "Blue");
	SensorType[color] = sensorColorNxtBLUE;
	wait1Msec(1000);
	displayCenteredBigTextLine(3, "RGB");
	SensorType[color] = sensorColorNxtFULL;
	while(true)
	{
		displayColor(SensorValue[color]);
		wait1Msec(250);
	}
}
