#pragma config(Sensor, S1,     light,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	eraseDisplay();
	displayCenteredBigTextLine(2, "light");
	while(true)
	{
		int light = SensorValue[light];
		displayCenteredBigTextLine(4, "%d",  light);
		wait1Msec(250);
	}
}
