#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	eraseDisplay();
	displayCenteredBigTextLine(2, "dist");
	while(true)
	{
		int dist = SensorValue[sonar];
		displayCenteredBigTextLine(4, "%d cm",  dist);
		wait1Msec(250);
	}
}
