#pragma config(Sensor, S1,     Left,           sensorTouch) //0
#pragma config(Sensor, S2,     Right,          sensorTouch) //1
#pragma config(Sensor, S3,     Up,             sensorTouch) //2
#pragma config(Sensor, S4,     Down,           sensorTouch) //3
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const byte b=6;
string s;

task main()
{
	setSessionPIN("1234");
	ubyte 	 bstate[b]={0,0,0,0,1,0};
	ubyte bstateOld[b]={0,0,0,0,1,0};
	eraseDisplay();
	waitUntil(nBTCurrentStreamIndex==0);
	playSoundFile("link.rso");
	while (true){
  	bstate[0]=SensorValue[Left];
  	bstate[1]=SensorValue[Right];
  	bstate[2]=SensorValue[Up];
  	bstate[3]=SensorValue[Down];
  	if (nNxtButtonPressed == kEnterButton){
  		if (bstate[4]) bstate[4]=0;
  		else bstate[4]=1;
  		waitUntil(nNxtButtonPressed == kNoButton);
  	}
  	switch (bstateOld[5]){
					case  1: s="Black"; break;
					case  2: s="Blue"; break;
					case  3: s="Green"; break;
					case  4: s="Yellow"; break;
					case  5: s="Red"; break;
					case  6: s="White"; break;
					default: s="Undefined" break;
	}
  	eraseDisplay();
  	displayTextLine(0,"Left  %d",bstate[0]);
		displayTextLine(1,"Right %d",bstate[1]);
		displayTextLine(2,"FWD   %d",bstate[2]);
		displayTextLine(3,"BWD   %d",bstate[3]);
		displayTextLine(4,"Claw  %d",bstate[4]);
		displayTextLine(5, "Connected");
		displayTextLine(6, s);
		cCmdMessageRead(bstateOld, 6, mailbox1);
		wait1Msec(10);
    cCmdMessageWriteToBluetooth(0,bstate,5,mailbox2);
  }
}
