#pragma config(Sensor, S1,     Left,           sensorTouch) //0
#pragma config(Sensor, S2,     Right,          sensorTouch) //1
#pragma config(Sensor, S3,     Up,             sensorTouch) //2
#pragma config(Sensor, S4,     Down,           sensorTouch) //3
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const byte b=4;

task main()
{
	playSound (soundBeepBeep);
	btConnect(1,"Snatcher");
	ubyte bstate[b];
	while (true){
  	bstate[0]=SensorValue[Left];
  	bstate[1]=SensorValue[Right];
  	bstate[2]=SensorValue[Up];
  	bstate[3]=SensorValue[Down];
    cCmdMessageWriteToBluetooth(1,bstate,b,mailbox1);
  }
}
